//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Garrett_P3.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class product
    {
        public int SKU { get; set; }
        public string Product_Name { get; set; }
        public string Description { get; set; }
        public string CategoryID { get; set; }
        public decimal Price { get; set; }
        public string ImageProduct { get; set; }
    }
}
